/*
ATIVAR FOREING KEYS TODA VEZ QUE ESTABELECER CONEXAO COM SERVIDOR
PRAGMA foreign_keys = ON
*/
---SIMULA A EXCLUSAO DO FUNCIONARIO DO SISTEMA DESATIVANDO ELE DAS SUAS FUNCOES
PRAGMA foreign_keys = ON;
UPDATE Funcionario
SET ativo = 0
WHERE EXISTS(SELECT id FROM Cadastro ca WHERE ca.numero_cpf= '466461086-68' AND ca.id = Funcionario.FK_Cadastro_id)

---DELETE DO RELATORIO DE ACIDENTE COM BASE NO SEU ID
DELETE FROM Relatorio_acidente
WHERE id = 1;