/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author luizk
 */
public class JanelaPrincipal extends javax.swing.JFrame {
	
	private byte cadastroSelecionado = 1;
	JanelaCadFuncionario telaCadFunc = null;
	JanelaCadCondutor telaCadCond = null;

	/**
	 * Creates new form JanelaPrincipal
	 */
	public JanelaPrincipal() {
		initComponents();
		maximizarJanela();
		goToMenu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelUniversal = new javax.swing.JPanel();
        jLabelLogoPic = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        painelExibicao = new javax.swing.JPanel();
        painelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMainCond = new javax.swing.JButton();
        jButtonMainFunc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonMainMapa = new javax.swing.JButton();
        jButtonMainTab = new javax.swing.JButton();
        jButtonMainGrap = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        painelEmBranco = new javax.swing.JPanel();
        painelCadastros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastros = new javax.swing.JTable();
        jButtonCadNovo = new javax.swing.JButton();
        jButtonCadEditar = new javax.swing.JButton();
        jButtonCadVoltar = new javax.swing.JButton();
        jCampoProcurarCad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        painelRelatorios = new javax.swing.JPanel();
        jPanelRelCentro = new javax.swing.JPanel();
        jPanelRelCentroBranco = new javax.swing.JPanel();
        jPanelRelMapa = new javax.swing.JPanel();
        jLabelMapa = new javax.swing.JLabel();
        jPanelRelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelRelGrafico = new javax.swing.JPanel();
        jLabelGrafico = new javax.swing.JLabel();
        jPanelRelLateral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jButtonRelQtdAcid = new javax.swing.JButton();
        jButtonRelGravAcid = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonRelTabela = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonRelBarras = new javax.swing.JButton();
        jButtonRelLinhas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jFormatHor2 = new javax.swing.JFormattedTextField();
        jFormatAreaY = new javax.swing.JFormattedTextField();
        jFormatHor1 = new javax.swing.JFormattedTextField();
        jFormatAreaX = new javax.swing.JFormattedTextField();
        jFormatData1 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(896, 504));

        painelUniversal.setBackground(new java.awt.Color(0, 0, 102));

        jLabelLogoPic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLogoPic.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GenericLogoTrsp.png"))); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 153, 153));
        jLabelTitulo.setText("Road Monitor Online");
        jLabelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelUniversalLayout = new javax.swing.GroupLayout(painelUniversal);
        painelUniversal.setLayout(painelUniversalLayout);
        painelUniversalLayout.setHorizontalGroup(
            painelUniversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUniversalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelLogoPic)
                .addGap(18, 18, 18)
                .addComponent(jLabelTitulo)
                .addContainerGap(1051, Short.MAX_VALUE))
        );
        painelUniversalLayout.setVerticalGroup(
            painelUniversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUniversalLayout.createSequentialGroup()
                .addGroup(painelUniversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelUniversalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogoPic))
                    .addGroup(painelUniversalLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelUniversal, java.awt.BorderLayout.PAGE_START);

        painelExibicao.setMinimumSize(new java.awt.Dimension(640, 360));
        painelExibicao.setPreferredSize(new java.awt.Dimension(1280, 720));
        painelExibicao.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButtonMainCond.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMainCond.setText("Condutor");
        jButtonMainCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainCondActionPerformed(evt);
            }
        });

        jButtonMainFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMainFunc.setText("Funcionario");
        jButtonMainFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMainCond, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMainFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMainCond, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatorios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButtonMainMapa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMainMapa.setText("Mapa de Calor");
        jButtonMainMapa.setActionCommand("MapaDeCalor");
        jButtonMainMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMapaActionPerformed(evt);
            }
        });

        jButtonMainTab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMainTab.setText("Tabelas");
        jButtonMainTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainTabActionPerformed(evt);
            }
        });

        jButtonMainGrap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMainGrap.setText("Graficos");
        jButtonMainGrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainGrapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMainMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMainGrap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMainMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainGrap, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(612, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        painelExibicao.add(painelPrincipal, "card6");

        javax.swing.GroupLayout painelEmBrancoLayout = new javax.swing.GroupLayout(painelEmBranco);
        painelEmBranco.setLayout(painelEmBrancoLayout);
        painelEmBrancoLayout.setHorizontalGroup(
            painelEmBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
        );
        painelEmBrancoLayout.setVerticalGroup(
            painelEmBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        painelExibicao.add(painelEmBranco, "card4");

        jTableCadastros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastros);

        jButtonCadNovo.setText("Novo");
        jButtonCadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadNovoActionPerformed(evt);
            }
        });

        jButtonCadEditar.setText("Editar");
        jButtonCadEditar.setEnabled(false);

        jButtonCadVoltar.setText("Voltar");
        jButtonCadVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadVoltarActionPerformed(evt);
            }
        });

        jCampoProcurarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoProcurarCadActionPerformed(evt);
            }
        });

        jLabel1.setText("Procurar:");

        javax.swing.GroupLayout painelCadastrosLayout = new javax.swing.GroupLayout(painelCadastros);
        painelCadastros.setLayout(painelCadastrosLayout);
        painelCadastrosLayout.setHorizontalGroup(
            painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadVoltar))
                .addGap(18, 18, 18)
                .addGroup(painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCampoProcurarCad, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        painelCadastrosLayout.setVerticalGroup(
            painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadNovo)
                    .addComponent(jCampoProcurarCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrosLayout.createSequentialGroup()
                        .addComponent(jButtonCadEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        painelExibicao.add(painelCadastros, "card5");

        jPanelRelCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelRelCentro.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelRelCentroBrancoLayout = new javax.swing.GroupLayout(jPanelRelCentroBranco);
        jPanelRelCentroBranco.setLayout(jPanelRelCentroBrancoLayout);
        jPanelRelCentroBrancoLayout.setHorizontalGroup(
            jPanelRelCentroBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        jPanelRelCentroBrancoLayout.setVerticalGroup(
            jPanelRelCentroBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanelRelCentro.add(jPanelRelCentroBranco, "card2");

        jLabelMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMapa.setText("MAPA");

        javax.swing.GroupLayout jPanelRelMapaLayout = new javax.swing.GroupLayout(jPanelRelMapa);
        jPanelRelMapa.setLayout(jPanelRelMapaLayout);
        jPanelRelMapaLayout.setHorizontalGroup(
            jPanelRelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRelMapaLayout.setVerticalGroup(
            jPanelRelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelRelCentro.add(jPanelRelMapa, "card3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelRelTabelaLayout = new javax.swing.GroupLayout(jPanelRelTabela);
        jPanelRelTabela.setLayout(jPanelRelTabelaLayout);
        jPanelRelTabelaLayout.setHorizontalGroup(
            jPanelRelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRelTabelaLayout.setVerticalGroup(
            jPanelRelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelRelCentro.add(jPanelRelTabela, "card4");

        jLabelGrafico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrafico.setText("GRAFICO");

        javax.swing.GroupLayout jPanelRelGraficoLayout = new javax.swing.GroupLayout(jPanelRelGrafico);
        jPanelRelGrafico.setLayout(jPanelRelGraficoLayout);
        jPanelRelGraficoLayout.setHorizontalGroup(
            jPanelRelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelGraficoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRelGraficoLayout.setVerticalGroup(
            jPanelRelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelGraficoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelRelCentro.add(jPanelRelGrafico, "card5");

        jPanelRelLateral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Filtros");

        jLabel3.setText("Data inicial:");

        jLabel4.setText("Data final:");

        jLabel5.setText("Horário de:");

        jLabel6.setText("Até:");

        jLabel7.setText("Área X:");

        jLabel8.setText("Y:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Mapa De Calor");

        jButtonRelQtdAcid.setText("Quantidade de Acidentes");
        jButtonRelQtdAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelQtdAcidActionPerformed(evt);
            }
        });

        jButtonRelGravAcid.setText("Gravidade dos Acidentes");
        jButtonRelGravAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelGravAcidActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Tabelas");

        jButtonRelTabela.setText("Todos Os Dados");
        jButtonRelTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelTabelaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Gráficos");

        jButtonRelBarras.setText("Barras");
        jButtonRelBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelBarrasActionPerformed(evt);
            }
        });

        jButtonRelLinhas.setText("Linhas");
        jButtonRelLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelLinhasActionPerformed(evt);
            }
        });

        try {
            jFormatHor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormatAreaY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormatHor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormatAreaX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormatData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelRelLateralLayout = new javax.swing.GroupLayout(jPanelRelLateral);
        jPanelRelLateral.setLayout(jPanelRelLateralLayout);
        jPanelRelLateralLayout.setHorizontalGroup(
            jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonRelQtdAcid, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(jButtonRelGravAcid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jButtonRelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFormatData1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                                                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jFormatHor1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                    .addComponent(jFormatAreaX))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jFormatHor2)
                                                    .addComponent(jFormatAreaY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 16, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jButtonRelLinhas, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jButtonRelBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRelLateralLayout.setVerticalGroup(
            jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormatData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormatHor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormatAreaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRelLateralLayout.createSequentialGroup()
                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jFormatHor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormatAreaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelQtdAcid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelGravAcid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelLinhas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelRelatoriosLayout = new javax.swing.GroupLayout(painelRelatorios);
        painelRelatorios.setLayout(painelRelatoriosLayout);
        painelRelatoriosLayout.setHorizontalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelRelatoriosLayout.setVerticalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelExibicao.add(painelRelatorios, "card5");

        getContentPane().add(painelExibicao, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainCondActionPerformed
        this.cadastroSelecionado = 1;
		mudarPainel(painelExibicao, painelCadastros);
    }//GEN-LAST:event_jButtonMainCondActionPerformed

    private void jLabelTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTituloMouseClicked
        this.goToMenu();
    }//GEN-LAST:event_jLabelTituloMouseClicked

    private void jButtonMainFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainFuncActionPerformed
        this.cadastroSelecionado = 2;
		mudarPainel(painelExibicao, painelCadastros);
    }//GEN-LAST:event_jButtonMainFuncActionPerformed

    private void jButtonMainMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMapaActionPerformed
        painelExibicao.removeAll();
		painelExibicao.add(painelRelatorios);
		goToRelatorioMapa();
		painelExibicao.repaint();
		painelExibicao.revalidate();
    }//GEN-LAST:event_jButtonMainMapaActionPerformed

    private void jButtonRelGravAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelGravAcidActionPerformed
        goToRelatorioMapa();
    }//GEN-LAST:event_jButtonRelGravAcidActionPerformed

    private void jButtonRelQtdAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelQtdAcidActionPerformed
        goToRelatorioMapa();
    }//GEN-LAST:event_jButtonRelQtdAcidActionPerformed

    private void jButtonCadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadNovoActionPerformed
		switch (this.cadastroSelecionado) {
			case 1:
				popupCadCondutor();
				break;
			case 2:
				popupCadFuncionario();
				break;
			default:
				break;
		}
    }//GEN-LAST:event_jButtonCadNovoActionPerformed

    private void jButtonMainTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainTabActionPerformed
        painelExibicao.removeAll();
		painelExibicao.add(painelRelatorios);
		goToRelatorioTabela();
		painelExibicao.repaint();
		painelExibicao.revalidate();
    }//GEN-LAST:event_jButtonMainTabActionPerformed

    private void jButtonRelTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelTabelaActionPerformed
        //goToRelatorioTabela();
		mudarPainel(jPanelRelCentro, jPanelRelTabela);
    }//GEN-LAST:event_jButtonRelTabelaActionPerformed

    private void jButtonMainGrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainGrapActionPerformed
        painelExibicao.removeAll();
		painelExibicao.add(painelRelatorios);
		goToRelatorioGrafico();
		painelExibicao.repaint();
		painelExibicao.revalidate();
    }//GEN-LAST:event_jButtonMainGrapActionPerformed

    private void jButtonRelBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelBarrasActionPerformed
        goToRelatorioGrafico();
    }//GEN-LAST:event_jButtonRelBarrasActionPerformed

    private void jButtonCadVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadVoltarActionPerformed
        goToMenu();
    }//GEN-LAST:event_jButtonCadVoltarActionPerformed

    private void jButtonRelLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelLinhasActionPerformed
        goToRelatorioGrafico();
    }//GEN-LAST:event_jButtonRelLinhasActionPerformed

    private void jCampoProcurarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoProcurarCadActionPerformed
        System.out.println("teste: " + this.jCampoProcurarCad.getText());
		//TODO terminar
    }//GEN-LAST:event_jCampoProcurarCadActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JanelaPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadEditar;
    private javax.swing.JButton jButtonCadNovo;
    private javax.swing.JButton jButtonCadVoltar;
    private javax.swing.JButton jButtonMainCond;
    private javax.swing.JButton jButtonMainFunc;
    private javax.swing.JButton jButtonMainGrap;
    private javax.swing.JButton jButtonMainMapa;
    private javax.swing.JButton jButtonMainTab;
    private javax.swing.JButton jButtonRelBarras;
    private javax.swing.JButton jButtonRelGravAcid;
    private javax.swing.JButton jButtonRelLinhas;
    private javax.swing.JButton jButtonRelQtdAcid;
    private javax.swing.JButton jButtonRelTabela;
    private javax.swing.JTextField jCampoProcurarCad;
    private javax.swing.JFormattedTextField jFormatAreaX;
    private javax.swing.JFormattedTextField jFormatAreaY;
    private javax.swing.JFormattedTextField jFormatData1;
    private javax.swing.JFormattedTextField jFormatHor1;
    private javax.swing.JFormattedTextField jFormatHor2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGrafico;
    private javax.swing.JLabel jLabelLogoPic;
    private javax.swing.JLabel jLabelMapa;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelRelCentro;
    private javax.swing.JPanel jPanelRelCentroBranco;
    private javax.swing.JPanel jPanelRelGrafico;
    private javax.swing.JPanel jPanelRelLateral;
    private javax.swing.JPanel jPanelRelMapa;
    private javax.swing.JPanel jPanelRelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCadastros;
    private javax.swing.JPanel painelCadastros;
    private javax.swing.JPanel painelEmBranco;
    private javax.swing.JPanel painelExibicao;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelRelatorios;
    private javax.swing.JPanel painelUniversal;
    // End of variables declaration//GEN-END:variables

	private void popupCadFuncionario() {
		if(telaCadFunc == null){
			telaCadFunc = new JanelaCadFuncionario();
			telaCadFunc.setDefaultCloseOperation(HIDE_ON_CLOSE);
		}
        telaCadFunc.setVisible(true);
	}
	
	private void popupCadCondutor() {
		if(telaCadCond == null){
			telaCadCond = new JanelaCadCondutor();
			telaCadCond.setDefaultCloseOperation(HIDE_ON_CLOSE);
		}
        telaCadCond.setVisible(true);
	}
	
	public void goToMenu(){
		painelExibicao.removeAll();
		painelExibicao.add(painelPrincipal);
		painelExibicao.repaint();
		painelExibicao.revalidate();
	}

	private void goToRelatorioMain() {
		painelRelatorios.removeAll();
		painelRelatorios.add(jPanelRelLateral);
		painelRelatorios.add(jPanelRelCentro);
		painelRelatorios.repaint();
		painelRelatorios.revalidate();
	}

	private void goToRelatorioMapa() {
		goToRelatorioMain();
		mudarPainel(jPanelRelCentro, jPanelRelMapa);
		// TODO Fazer essa coisa funcionar, maybe
	}

	private void goToRelatorioTabela() {
		goToRelatorioMain();
		mudarPainel(jPanelRelCentro, jPanelRelTabela);
	}

	private void goToRelatorioGrafico() {
		goToRelatorioMain();
		mudarPainel(jPanelRelCentro, jPanelRelGrafico);
		// TODO Fazer essa coisa funcionar, maybe
	}
	
	private void mudarPainel(JPanel painelPai, JPanel painelFilho){
		painelPai.removeAll();
		painelPai.add(painelFilho);
		painelPai.repaint();
		painelPai.revalidate();
	}

	private void maximizarJanela() {
		this.setExtendedState( this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
	}

}
